### ISSUE TITLE
File I/O: Switch to O_DIRECT

### ISSUE THREAD

**Issue by kp6** [rancher/sparse-tools#6]
The direct I/O requires some support for aligned memory allocation in golang

**Comment by ibuildthecloud** [comment]
I found this package, personally experimenting with it https://github.com/ncw/directio, just a FYI

**Comment by kp6** [comment]
I put something similar together in the hash branch in dfile package

-----Original Message-----

**Comment by kp6** [comment]
switched in commit 9e7beab60f561c9a71b71971d8bdc0be6e798417
